allowBuilds:
  esbuild: true
  workerd: true

minimumReleaseAgeExclude:
  - wrangler@4.145.0
  - workerd@1.20260930.2
  - miniflare@5.20260930.0-alpha
  - '@cloudflare/workerd-darwin-64@1.20260930.2'
  - '@cloudflare/workerd-darwin-arm64@1.20260930.2'
  - '@cloudflare/workerd-linux-64@1.20260930.2'
  - '@cloudflare/workerd-linux-arm64@1.20260930.2'
  - '@cloudflare/workerd-windows-64@1.20260930.2'
